# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170122_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=4000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
