# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170122_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='info',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
